image: ${CI_REGISTRY}/code/ci-images/maven:1.0.5

stages:
  - build
  - test
  - deploy

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  MAVEN_CLI_OPTS: "-s /opt/settings.xml --batch-mode --errors --fail-at-end --show-version -Dmaven.install.skip=true"
  ENVIRONMENT: "ci"

# reuse the dependencies and artifacts
cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS --update-snapshots clean compile test-compile
  tags:
    - t3.small
  artifacts:
    paths:
      - '*/*/target'

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  tags:
    - t3.large
  cache:
    policy: pull
  dependencies:
    - build
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml

deploy:
  stage: deploy
  tags:
    - t3.small
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests -DskipAssembly=true -Dmaven.install.skip=true -Drevision=${CI_COMMIT_TAG} deploy
  only:
    - tags
  dependencies:
    - test

